# Generated by Django 5.1.5 on 2025-02-08 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crouirouge', '0002_redcrossleader'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'Family', 'verbose_name_plural': 'Families'},
        ),
        migrations.AlterModelOptions(
            name='familyactivities',
            options={'verbose_name': 'Family Activity', 'verbose_name_plural': 'Family Activities'},
        ),
        migrations.AlterModelOptions(
            name='fellowership',
            options={'verbose_name': 'Fellowship', 'verbose_name_plural': 'Fellowships'},
        ),
        migrations.AlterModelOptions(
            name='firstaidcourse',
            options={'verbose_name': 'First Aid Course', 'verbose_name_plural': 'First Aid Courses'},
        ),
        migrations.AlterModelOptions(
            name='instructors',
            options={'verbose_name': 'Instructor', 'verbose_name_plural': 'Instructors'},
        ),
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AlterModelOptions(
            name='redcrossactivities',
            options={'verbose_name': 'Redcross Activity', 'verbose_name_plural': 'Redcross Activities'},
        ),
        migrations.AlterModelOptions(
            name='redcrossleader',
            options={'verbose_name': 'Redcross Leader', 'verbose_name_plural': 'Redcross Leaders'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
