# Generated by Django 5.1.5 on 2025-02-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crouirouge', '0005_alter_messages_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='status',
            field=models.CharField(default='unread', max_length=20),
        ),
    ]
