# Generated by Django 5.1.5 on 2025-02-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crouirouge', '0006_messages_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('President', 'President'), ('Vice President', 'Vice President'), ('admin', 'admin'), ('child', 'child')], default='child', max_length=120),
        ),
    ]
