# Generated by Django 5.1.5 on 2025-02-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crouirouge', '0007_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeNewslatter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subscribe Newslatter',
                'verbose_name_plural': 'Subscribe Newslatters',
            },
        ),
    ]
