# Generated by Django 5.1.5 on 2025-03-08 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crouirouge', '0009_alter_user_email_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=120)),
                ('district', models.CharField(max_length=120)),
                ('sector', models.CharField(max_length=120)),
                ('cell', models.CharField(max_length=120)),
                ('village', models.CharField(max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BloodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donated', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=120)),
                ('donated_times', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blood_donation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Generalinformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationalId', models.IntegerField(unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=120)),
                ('department', models.CharField(max_length=120)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='general_information', to='crouirouge.address')),
                ('blood_donated', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='general_information', to='crouirouge.blooddonation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='general_information', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'General Information',
                'verbose_name_plural': 'General Informations',
            },
        ),
    ]
