# Generated by Django 5.1.5 on 2025-03-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crouirouge', '0011_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Member', 'Member'), ('President', 'President'), ('Vice President', 'Vice President'), ('admin', 'admin'), ('child', 'child')], default='child', max_length=120),
        ),
    ]
