# Generated by Django 5.1.5 on 2025-03-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crouirouge', '0012_alter_user_role_requestmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribenewslatter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
