# Generated by Django 5.1.5 on 2025-03-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crouirouge', '0013_subscribenewslatter_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Messages'},
        ),
        migrations.AddField(
            model_name='messages',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messages',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
